import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

type Items = SidebarsConfig[string];
type Item = {type: string; id?: string};

/** Standard sidebar every project gets: hand-written guides + generated API reference. */
export function projectSidebar(projectDir: string): Items {
  // Generated by `npm run gen-api` (docusaurus-plugin-openapi-docs).
  const apiSidebar = path.join(projectDir, 'docs/api/sidebar.ts');
  const api: Item[] = fs.existsSync(apiSidebar) ? require(apiSidebar).default : [];
  const info = api.find((i) => i.type === 'doc');
  return [
    'intro',
    'getting-started',
    'architecture',
    'integrations',
    'changelog',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      ...(info && {link: {type: 'doc', id: info.id}}),
      items: api.filter((i) => i !== info),
    },
  ] as Items;
}
