import fs from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

type Items = SidebarsConfig[string];
type Item = {type: string; id?: string};

/**
 * Sidebar for any API project: whatever guides exist in its docs folder (ordered by
 * `sidebar_position`), followed by the API reference generated from its OpenAPI spec.
 */
export function projectSidebar(docsDir: string): Items {
  const guides = fs
    .readdirSync(docsDir)
    .filter((f) => /\.mdx?$/.test(f))
    .map((f) => {
      const src = fs.readFileSync(path.join(docsDir, f), 'utf8');
      const pos = Number(src.match(/^sidebar_position:\s*(\d+)/m)?.[1] ?? 99);
      return {id: f.replace(/\.mdx?$/, ''), pos};
    })
    .sort((a, b) => a.pos - b.pos || a.id.localeCompare(b.id))
    .map((g) => g.id);

  // Generated by `npm run gen-api` (docusaurus-plugin-openapi-docs).
  const apiSidebar = path.join(docsDir, 'api/sidebar.ts');
  const api: Item[] = fs.existsSync(apiSidebar) ? require(apiSidebar).default : [];
  const info = api.find((i) => i.type === 'doc');
  return [
    ...guides,
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      ...(info && {link: {type: 'doc', id: info.id}}),
      items: api.filter((i) => i !== info),
    },
  ] as Items;
}
