import React from 'react';
import Link from '@docusaurus/Link';
import {useProject} from '@site/src/hooks/useCatalog';
import styles from './styles.module.css';

/**
 * Cross-project link to an OpenAPI operation, resolved from the catalog at build time.
 * Usage in MDX: <ApiRef project="accounts" op="getBalances" />
 */
export default function ApiRef({project, op}: {project: string; op: string}) {
  const p = useProject(project);
  const o = p.operations.find((x) => x.operationId === op);
  if (!o) throw new Error(`ApiRef: ${project} has no operation "${op}"`);
  return (
    <Link to={o.url} className={styles.ref} title={`${p.name}: ${o.summary}`}>
      <span className={`${styles.method} ${styles[o.method.toLowerCase()]}`}>{o.method}</span>
      <code className={styles.path}>{o.path}</code>
      <span className={styles.project}>{p.name}</span>
    </Link>
  );
}

/** Table of every operation a project exposes, for embedding in any page. */
export function OperationTable({project}: {project: string}) {
  const p = useProject(project);
  return (
    <table>
      <thead>
        <tr><th>Operation</th><th>Endpoint</th><th>Tag</th></tr>
      </thead>
      <tbody>
        {p.operations.map((o) => (
          <tr key={o.operationId}>
            <td><Link to={o.url}>{o.summary}</Link></td>
            <td>
              <span className={`${styles.method} ${styles[o.method.toLowerCase()]}`}>{o.method}</span>{' '}
              <code>{o.path}</code>
            </td>
            <td>{o.tags.join(', ')}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/** Link to a shared/project schema page generated by the OpenAPI plugin. */
export function SchemaRef({project, name}: {project: string; name: string}) {
  const p = useProject(project);
  if (!p.schemas.includes(name)) throw new Error(`SchemaRef: ${project} has no schema "${name}"`);
  return (
    <Link to={`/${project}/api/schemas/${name.toLowerCase()}`} className={styles.ref}>
      <span className={`${styles.method} ${styles.schema}`}>SCHEMA</span>
      <code className={styles.path}>{name}</code>
      <span className={styles.project}>{p.name}</span>
    </Link>
  );
}
